ERROR 2025-09-28 08:13:30,124 middleware 11560 856 Unhandled exception: no such column: orders_order.status
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: orders_order.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\accounts\views.py", line 113, in customer_profile
    return render(request, 'accounts/profile.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: orders_order.status
ERROR 2025-09-28 08:13:30,160 log 11560 856 Internal Server Error: /accounts/profile/
ERROR 2025-09-28 08:13:30,161 basehttp 11560 856 "GET /accounts/profile/ HTTP/1.1" 500 10562
ERROR 2025-09-28 08:13:52,148 middleware 11560 856 Unhandled exception: no such column: orders_order.status
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: orders_order.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\accounts\views.py", line 113, in customer_profile
    return render(request, 'accounts/profile.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: orders_order.status
ERROR 2025-09-28 08:13:52,157 log 11560 856 Internal Server Error: /accounts/profile/
ERROR 2025-09-28 08:13:52,158 basehttp 11560 856 "GET /accounts/profile/ HTTP/1.1" 500 10562
ERROR 2025-09-28 08:14:41,072 middleware 11560 856 Unhandled exception: no such column: orders_order.status
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: orders_order.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\accounts\views.py", line 113, in customer_profile
    return render(request, 'accounts/profile.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: orders_order.status
ERROR 2025-09-28 08:14:41,080 log 11560 856 Internal Server Error: /accounts/profile/
ERROR 2025-09-28 08:14:41,080 basehttp 11560 856 "GET /accounts/profile/ HTTP/1.1" 500 10562
ERROR 2025-09-28 08:15:08,203 middleware 11560 856 Unhandled exception: no such column: orders_order.status
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: orders_order.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\accounts\views.py", line 113, in customer_profile
    return render(request, 'accounts/profile.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: orders_order.status
ERROR 2025-09-28 08:15:08,220 log 11560 856 Internal Server Error: /accounts/profile/
ERROR 2025-09-28 08:15:08,221 basehttp 11560 856 "GET /accounts/profile/ HTTP/1.1" 500 10562
ERROR 2025-09-28 08:15:41,040 middleware 11560 35428 Unhandled exception: no such column: orders_order.status
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: orders_order.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\accounts\views.py", line 113, in customer_profile
    return render(request, 'accounts/profile.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: orders_order.status
ERROR 2025-09-28 08:15:41,049 log 11560 35428 Internal Server Error: /accounts/profile/
ERROR 2025-09-28 08:15:41,050 basehttp 11560 35428 "GET /accounts/profile/ HTTP/1.1" 500 10944
ERROR 2025-09-28 08:16:09,247 middleware 11560 35428 Unhandled exception: no such column: orders_order.status
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: orders_order.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\accounts\views.py", line 113, in customer_profile
    return render(request, 'accounts/profile.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: orders_order.status
ERROR 2025-09-28 08:16:09,260 log 11560 35428 Internal Server Error: /accounts/profile/
ERROR 2025-09-28 08:16:09,261 basehttp 11560 35428 "GET /accounts/profile/ HTTP/1.1" 500 10860
ERROR 2025-09-28 08:16:13,943 middleware 11560 35428 Unhandled exception: no such column: orders_order.status
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    raise TypeError
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 243, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'order'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: orders_order.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 16, in wrap
    return function(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 43, in vendor_dashboard
    return render(request, 'shop/vendor_dashboard.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 901, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 261, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 224, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: orders_order.status
ERROR 2025-09-28 08:16:13,995 log 11560 35428 Internal Server Error: /shop/dashboard/
ERROR 2025-09-28 08:16:13,997 basehttp 11560 35428 "GET /shop/dashboard/ HTTP/1.1" 500 10860
ERROR 2025-09-28 08:16:18,727 middleware 11560 35428 Unhandled exception: no such column: orders_order.status
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    raise TypeError
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 243, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'order'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: orders_order.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 16, in wrap
    return function(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 43, in vendor_dashboard
    return render(request, 'shop/vendor_dashboard.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 901, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 261, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 224, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: orders_order.status
ERROR 2025-09-28 08:16:18,739 log 11560 35428 Internal Server Error: /shop/dashboard/
ERROR 2025-09-28 08:16:18,740 basehttp 11560 35428 "GET /shop/dashboard/ HTTP/1.1" 500 10860
ERROR 2025-09-28 09:36:55,015 middleware 30316 27808 Unhandled exception: name 'models' is not defined
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 15, in wrap
    return function(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 48, in vendor_dashboard
    total_sold=Sum('order_items__quantity', filter=models.Q(order_items__order__paid=True))
                                                   ^^^^^^
NameError: name 'models' is not defined
ERROR 2025-09-28 09:36:55,037 log 30316 27808 Internal Server Error: /shop/dashboard/
ERROR 2025-09-28 09:36:55,038 basehttp 30316 27808 "GET /shop/dashboard/ HTTP/1.1" 500 13808
ERROR 2025-09-28 09:36:59,469 middleware 30316 27808 Unhandled exception: name 'models' is not defined
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 15, in wrap
    return function(request, *args, **kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 48, in vendor_dashboard
    total_sold=Sum('order_items__quantity', filter=models.Q(order_items__order__paid=True))
                                                   ^^^^^^
NameError: name 'models' is not defined
ERROR 2025-09-28 09:36:59,473 log 30316 27808 Internal Server Error: /shop/dashboard/
ERROR 2025-09-28 09:36:59,473 basehttp 30316 27808 "GET /shop/dashboard/ HTTP/1.1" 500 13808
ERROR 2025-09-28 11:08:20,805 middleware 13052 12172 Unhandled exception: Could not parse the remainder: '=='featured'' from 'sort_by=='featured''
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "sort_by=='featured'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 40, in vendor_storefront
    return render(request, 'shop/vendor_storefront.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=='featured'' from 'sort_by=='featured''
ERROR 2025-09-28 11:08:20,891 log 13052 12172 Internal Server Error: /shop/vendor/2/
ERROR 2025-09-28 11:08:20,892 basehttp 13052 12172 "GET /shop/vendor/2/ HTTP/1.1" 500 13418
ERROR 2025-09-28 11:11:09,322 middleware 13052 35400 Unhandled exception: Could not parse the remainder: '=='featured'' from 'sort_by=='featured''
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "sort_by=='featured'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 40, in vendor_storefront
    return render(request, 'shop/vendor_storefront.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=='featured'' from 'sort_by=='featured''
ERROR 2025-09-28 11:11:09,339 log 13052 35400 Internal Server Error: /shop/vendor/2/
ERROR 2025-09-28 11:11:09,339 basehttp 13052 35400 "GET /shop/vendor/2/ HTTP/1.1" 500 13418
ERROR 2025-09-28 11:13:42,722 middleware 13052 31416 Unhandled exception: Could not parse the remainder: '=='featured'' from 'sort_by=='featured''
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "sort_by=='featured'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 40, in vendor_storefront
    return render(request, 'shop/vendor_storefront.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=='featured'' from 'sort_by=='featured''
ERROR 2025-09-28 11:13:42,732 log 13052 31416 Internal Server Error: /shop/vendor/2/
ERROR 2025-09-28 11:13:42,733 basehttp 13052 31416 "GET /shop/vendor/2/ HTTP/1.1" 500 13418
ERROR 2025-09-28 11:14:07,121 middleware 13052 31416 Unhandled exception: Could not parse the remainder: '=='featured'' from 'sort_by=='featured''
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "sort_by=='featured'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\shop\views.py", line 40, in vendor_storefront
    return render(request, 'shop/vendor_storefront.html', context)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\ZENER\Documents\dEVs\linkup_gadgets\.venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=='featured'' from 'sort_by=='featured''
ERROR 2025-09-28 11:14:07,138 log 13052 31416 Internal Server Error: /shop/vendor/2/
ERROR 2025-09-28 11:14:07,139 basehttp 13052 31416 "GET /shop/vendor/2/ HTTP/1.1" 500 13418
ERROR 2025-09-28 15:44:18,178 log 4228 20620 Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\base.css'
ERROR 2025-09-28 15:44:18,179 log 4228 17136 Internal Server Error: /static/admin/css/dark_mode.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\dark_mode.css'
ERROR 2025-09-28 15:44:18,181 log 4228 20104 Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\nav_sidebar.css'
ERROR 2025-09-28 15:44:18,182 log 4228 18020 Internal Server Error: /static/admin/css/login.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\login.css'
ERROR 2025-09-28 15:44:18,184 log 4228 19732 Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\responsive.css'
ERROR 2025-09-28 15:44:18,193 basehttp 4228 17136 "GET /static/admin/css/dark_mode.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:18,193 basehttp 4228 20620 "GET /static/admin/css/base.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:18,204 basehttp 4228 19732 "GET /static/admin/css/responsive.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:18,202 basehttp 4228 18020 "GET /static/admin/css/login.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:18,194 basehttp 4228 20104 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:20,982 log 4228 1676 Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\base.css'
ERROR 2025-09-28 15:44:20,985 log 4228 17656 Internal Server Error: /static/admin/css/dark_mode.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\dark_mode.css'
ERROR 2025-09-28 15:44:20,988 log 4228 18788 Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\nav_sidebar.css'
ERROR 2025-09-28 15:44:20,990 log 4228 11804 Internal Server Error: /static/admin/css/login.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\login.css'
ERROR 2025-09-28 15:44:20,991 basehttp 4228 1676 "GET /static/admin/css/base.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:20,994 log 4228 18308 Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\responsive.css'
ERROR 2025-09-28 15:44:20,997 basehttp 4228 17656 "GET /static/admin/css/dark_mode.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,001 basehttp 4228 18788 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,003 basehttp 4228 11804 "GET /static/admin/css/login.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,010 basehttp 4228 18308 "GET /static/admin/css/responsive.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,188 log 4228 16652 Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\base.css'
ERROR 2025-09-28 15:44:21,192 log 4228 11464 Internal Server Error: /static/admin/css/dark_mode.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\dark_mode.css'
ERROR 2025-09-28 15:44:21,192 basehttp 4228 16652 "GET /static/admin/css/base.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,195 log 4228 17716 Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\nav_sidebar.css'
ERROR 2025-09-28 15:44:21,205 basehttp 4228 17716 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,201 basehttp 4228 11464 "GET /static/admin/css/dark_mode.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,202 log 4228 19872 Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\responsive.css'
ERROR 2025-09-28 15:44:21,198 log 4228 21428 Internal Server Error: /static/admin/css/login.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\login.css'
ERROR 2025-09-28 15:44:21,213 basehttp 4228 19872 "GET /static/admin/css/responsive.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,213 basehttp 4228 21428 "GET /static/admin/css/login.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,298 log 4228 21408 Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\base.css'
ERROR 2025-09-28 15:44:21,300 log 4228 5456 Internal Server Error: /static/admin/css/dark_mode.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\dark_mode.css'
ERROR 2025-09-28 15:44:21,301 basehttp 4228 21408 "GET /static/admin/css/base.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,303 log 4228 3584 Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\nav_sidebar.css'
ERROR 2025-09-28 15:44:21,306 basehttp 4228 5456 "GET /static/admin/css/dark_mode.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,306 log 4228 21456 Internal Server Error: /static/admin/css/login.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\login.css'
ERROR 2025-09-28 15:44:21,308 log 4228 16772 Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\responsive.css'
ERROR 2025-09-28 15:44:21,309 basehttp 4228 3584 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,317 basehttp 4228 16772 "GET /static/admin/css/responsive.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:21,319 basehttp 4228 21456 "GET /static/admin/css/login.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:32,135 log 4228 9864 Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\base.css'
ERROR 2025-09-28 15:44:32,138 log 4228 13700 Internal Server Error: /static/admin/css/dark_mode.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\dark_mode.css'
ERROR 2025-09-28 15:44:32,141 log 4228 9048 Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\nav_sidebar.css'
ERROR 2025-09-28 15:44:32,142 basehttp 4228 9864 "GET /static/admin/css/base.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:32,145 log 4228 21372 Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 122, in __call__
    return self.serve(static_file, request)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\middleware.py", line 127, in serve
    response = static_file.get_response(request.method, request.META)
  File "C:\Users\ZENER\Documents\dEVs\JS\linkup_gadgets\.venv\Lib\site-packages\whitenoise\responders.py", line 86, in get_response
    file_handle = open(path, "rb")  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZENER\\Documents\\dEVs\\linkup_gadgets\\staticfiles\\admin\\css\\responsive.css'
ERROR 2025-09-28 15:44:32,151 basehttp 4228 13700 "GET /static/admin/css/dark_mode.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:32,151 basehttp 4228 9048 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 500 145
ERROR 2025-09-28 15:44:32,153 basehttp 4228 21372 "GET /static/admin/css/responsive.css HTTP/1.1" 500 145
